#!/usr/bin/env bash

# check if the statement is not provided 

if [ -z "$1" ]; then
    echo "argument not provided"
else
    export VPC_ID="$1"
fi

# delete vpc

aws ec2 delete-vpc --vpc-id $VPC_ID --region eu-central-1